export enum ErrorCode {
  INVALID_TOKEN = "INVALID_TOKEN",
  NOT_FOUND = "NOT_FOUND",
  EXPIRED_TOKEN = "EXPIRED_TOKEN",
  LIMITED_PERMISSION = "LIMITED_PERMISSION",
  DELETED_ITEM = "DELETED_ITEM",
  INVALID_RELATION = "INVALID_RELATION",
  UNIQUE_CONSTRAINT = "UNIQUE_CONSTRAINT",
}
